package com.robosh.distancebetween.application

const val INTENT_USERNAME = "INTENT_USERNAME"
const val INTENT_ACCEPT_DIALOG_USERNAME = "INTENT_ACCEPT_DIALOG_USERNAME"
const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
const val ACCESS_FINE_LOCATION_PERMISSION_CODE = 20
const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
const val NOTIFICATION_ID = 110
const val ACTION_SHOW_DISTANCE_BETWEEN_FRAGMENT = "ACTION_SHOW_DISTANCE_BETWEEN_FRAGMENT"
const val INTENT_USER_FOR_SERVICE = "INTENT_USER_FOR_SERVICE"
const val ACCEPT_CONNECTION_DIALOG_TAG = "ACCEPT_CONNECTION_DIALOG_TAG"